version: "3.1"

services:
  
  aerospike:
    image: aerospike/aerospike-server
    hostname: aerospike
    container_name: aerospike
    ports:
      - "3000:3000"
    volumes: 
      - $PWD:/etc/aerospike
  
  amc:
    image: aerospike/amc
    hostname: amc
    container_name: amc
    ports:
      - "8081:8081"
    depends_on:
      - aerospike